<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
            schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mrpt_slam</name>
  <version>0.1.20</version>
  <description>
    ROS 2 wrappers for SLAM algorithms from the MRPT library.
    This is a metapackage grouping all mrpt_slam algorithm packages.
  </description>
  <maintainer email="v.d.tananaev@gmail.com">Vladislav Tananaev</maintainer>
  <maintainer email="jlblanco@ual.es">Jose Luis Blanco Claraco</maintainer>

  <license>BSD</license>

  <url type="website">http://ros.org/wiki/mrpt_slam</url>
  <url type="bugtracker">https://github.com/mrpt-ros-pkg/mrpt_slam/issues</url>

  <author email="v.d.tananaev@gmail.com">Vladislav Tananaev</author>
  <author email="jlblanco@ual.es">Jose Luis Blanco Claraco</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>mrpt_ekf_slam_2d</exec_depend>
  <exec_depend>mrpt_ekf_slam_3d</exec_depend>
  <exec_depend>mrpt_icp_slam_2d</exec_depend>
  <exec_depend>mrpt_rbpf_slam</exec_depend>
  <exec_depend>mrpt_graphslam_2d</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
