// Copyright (c) 2024-2026, Jose Luis Blanco-Claraco.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

/* +---------------------------------------------------------------------------+
   |                     Mobile Robot Programming Toolkit (MRPT)               |
   |                          http://www.mrpt.org/                             |
   |                                                                           |
   | Copyright (c) 2005-2016, Individual contributors, see AUTHORS file        |
   | See: http://www.mrpt.org/Authors - All rights reserved.                   |
   | Released under BSD License. See details in http://www.mrpt.org/License    |
   +---------------------------------------------------------------------------+
 */
#pragma once

#include <rclcpp/rclcpp.hpp>
#include <nav_msgs/msg/occupancy_grid.hpp>
#include <nav_msgs/msg/path.hpp>
#include <mrpt/ros2bridge/map.h>
#include <mrpt_msgs/msg/graph_slam_agents.hpp>
#include <mrpt/system/COutputLogger.h>
#include <mrpt/maps/COccupancyGridMap2D.h>
#include <mrpt/math/utils.h>

namespace mrpt
{
namespace graphslam
{
/**\brief Struct holding a COccupancyGridMap2D (as well as subscribers for
 * updating it) for a specific running GraphSlamAgent instance.
 *
 * \note used in the global map-merging procedure
 */
struct TNeighborAgentMapProps
{
  TNeighborAgentMapProps(
    mrpt::system::COutputLogger * logger_in,
    const mrpt_msgs::msg::GraphSlamAgent & agent_in,
    rclcpp::Node * node_in);

  void readROSParameters();
  void setupComm();
  void setupSubs();
  void setupPubs();
        /**\brief Callback method to be called when new data in the map topic is
         * available
         */
  void updateGridMap(nav_msgs::msg::OccupancyGrid::SharedPtr nav_gridmap);
        /**\brief Callback method to be called when new data in the Estimated
         * Trajectory topic is available
         */
  void updateRobotTrajectory(nav_msgs::msg::Path::SharedPtr nav_robot_traj);

        /**\brief Return how many nodes have been registered in the fetched robot
         * trajectory
         */
  size_t getNodeCount()
  {
    return nav_robot_trajectory ? nav_robot_trajectory->poses.size() : 0;
  }

  mrpt::system::COutputLogger * m_logger;
  rclcpp::Node * nh;
        /**\brief Copy of the GraphSlamAgent instance of the neighbor */
  const mrpt_msgs::msg::GraphSlamAgent agent;
        /**\brief Map generated by the corresponding agent - in ROS form */
  nav_msgs::msg::OccupancyGrid::SharedPtr nav_map;
        /**\brief Trajectory of the correspondign agent - in ROS form */
  nav_msgs::msg::Path::SharedPtr nav_robot_trajectory;
        /**\name Subscriber instances */
        /**\{ */
  rclcpp::Subscription<nav_msgs::msg::OccupancyGrid>::SharedPtr map_sub;
  rclcpp::Subscription<nav_msgs::msg::Path>::SharedPtr robot_trajectory_sub;
        /**\} */
        /**\name Topic names */
        /**\{ */
  std::string map_topic;
  std::string robot_trajectory_topic;
        /**\} */
  size_t queue_size;
  bool has_init_class;
  bool has_setup_comm;

};      // end of TNeighborAgentMapProps

}  // namespace graphslam
}  // namespace mrpt
